### ISSUE TITLE
Broken Menu Items

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/archstrike-menu#1]
--- Info Gather ---
- [ ] fragrouter - not a (pkg)
- [x] miranda
- [x] thcping6
- [ ] casefile
- [x] maltego
- [x] metagoofil
- [ ] twofi
- [x] intrace - in testing as intrace-git
- [x] irpas-ass - in main as irpas
- [x] ipass-cdp - in main as irpas
- [ ] smbmap - Waiting for updated tag
- [ ] smtp-user-enum in testing 
- [ ] onesixtyone in testing
- [ ] snmp-check - not a (pkg)
- [ ] sparta in testing broken due to https://github.com/ArchStrike/ArchStrike/issues/278

--- Vuln Analysis ---
- [ ] CAT (cisco-audit-tool) - not a (pkg)
- [ ] cge (cisco-global-exploiter) - not a (pkg)
- [ ] sfuzz - in testing
- [ ] siparmyknife - not a (pkg)
- [ ] spike-generic_chunked - in testing
- [ ] spike-generic_listen_tcp - in testing
- [ ] spike-generic_send_tcp - in testing
- [ ] spike-generic_send_udp - in testing
- [ ] nessus - not a (pkg)
- [ ] thc-ssl-dos - in testing
- [x] protos-sip - in testing
- [ ] rtpbreak  
- [ ] rtpflood
- [ ] rtpinsertsound
- [ ] rtpmixsound
- [x] sctpscan - in testing as sctpscan-git
- [x] sipp - in testing
- [x] sipsak - in testing
- [ ] svcrack - in testing as sipvicious
- [ ] svcrash - in testing as sipvicious
- [ ] svmap - in testing as sipvicious
- [ ] svreport - in testing as sipvicious
- [ ] svwar - in testing as sipvicious
- [x] viophopper - in testing

--- Web App ---
- [ ] plecost - busted per https://github.com/ArchStrike/ArchStrike/issues/285
- [ ] ua-tester - not a (pkg)
- [ ] proxysite - not a (pkg)
- [ ] apache-users - not a (pkg)
- [ ] cutycapt - busted per https://github.com/ArchStrike/ArchStrike/issues/278
- [ ] uniscan - in testing
- [ ] watobo - not a (pkg)
- [ ] webslayer - not a (pkg)
- [ ] fimap - not  a (pkg)
- [x] owasp-mantra-ff - remove busted old pkg, wont fix
- [ ] padbuster - in testing
- [ ] vega - busted per https://github.com/ArchStrike/ArchStrike/issues/288
- [ ] w3af - busted per https://github.com/ArchStrike/ArchStrike/issues/278
- [ ] webscarab - busted per https://github.com/ArchStrike/ArchStrike/issues/300

--- Database Assessment ---
- [ ] hexorbase - not a (pkg)
- [ ] mdb-sql - not a (pkg)
- [ ] oscanner -  not a (pkg)
- [ ] sqldict - not a (pkg)
- [ ] sqlsus - not a (pkg)
- [x] tnscmd10g - in testing

--- Password Attack ---
- [ ] cachedump - not a (pkg)
- [ ] lsadump - not a (pkg)
- [ ] sipcrack - in testing
- [ ] truecrack - not a (pkg)
- [ ] keimpx - in testing as keimpx-git
- [ ] phrasendresher in main
- [x] pth-curl - remove
- [x] pth-net - remove
- [x] pth-openchangeclient - remove
- [x] pth-rpcclient - remove
- [x] pth-smbclient - remove
- [x] pth-smbget - remove
- [x] pth-sqsh - remove
- [x] pth-winexe - remove
- [x] pth-wmic - remove
- [x] pth-wmis - remove
- [x] pth-xfreerdp - remove
- [ ] smbmap - in testing
- [ ] cewl - in testing

--- Wireless ---
- [ ] fern
- [ ] gikismet - not a (pkg)
- [ ] wifi-honey - in testing
- [ ] bluelog - not a (pkg)
- [ ] bluemaho - not a (pkg)
- [ ] bluesnarfer - in testing
- [ ] spooftooph - in testing
- [ ] zbassofcflood - not a (pkg)
- [ ] zbdsniff - not a (pkg)
- [ ] zbdump - not a(pkg)
- [ ] zbfind - not a (pkg)
- [ ] zbgoodfind - not a (pkg)
- [ ] zbreplay - not a (pkg)
- [ ] zbstumbler - not a (pkg)
- [ ] mfoc - in testing
- [ ] miflare-classic-format - not a (pkg)
- [ ] chirp - not a (pkg)
- [ ] gr-scan - not a (pkg)
- [ ] modes_gui - not a (pkg)
- [ ] rtlsdr-scanner - busted due to https://github.com/ArchStrike/ArchStrike/issues/278
- [ ] ghost phisher - busted due to https://github.com/ArchStrike/ArchStrike/issues/278

--- RE ---
- [x] apktool - not a pkg, remove cant pkg this 
- [x] javasnoop - in main
- [ ] recstudio - in testing

--- Exploit ---
- [x] metasploit - in archstrike-meta pkg
- [x] msf payload creator - in main called metasploit-payload-creator
- [ ] sandi-gui - in testing 
- [ ] termineter - in testing

---  Sniff & Spoof ---
- [ ] sslsniff - in testing
- [ ] dns-rebind - in testing
- [ ] sniffjoke - in testing
- [ ] tcpreplay - in archstrike-meta pkg
- [x] ferret - remove, cant find src
- [x] hamster - remove cant find src

--- Post Exploit ---
- [ ] u3-pwn - not a (pkg)
- [ ] exe2hex - not a (pkg)
- [ ] stunnel4 - in archstrike-meta pkg
- [ ] webacoo - in testing 
- [ ] veil-catapult (not a pkg)
- [ ] veil-evasion (not a pkg)

--- Forensics ---
- [ ] readpst - not a (pkg)
- [ ] reglookup - in testing
- [ ] regripper - not a (pkg)
- [ ] vinetto - in testing
- [x] pev - in main
- [ ] rifiuti - in testing
- [ ] rifiuti2 - in testing
- [ ] volalfox - in testing
- [x] xplico - remove this is a pain to pkg, pkg
--sleuthkit--
	- [ ] bulk_extractor
	- [ ] blkcalc
	- [ ] blkcat
	- [ ] blkls
	- [ ] ffind
	- [ ] fls
	- [ ] fsstat
	- [ ] icat
	- [ ] ifind
	- [ ] ils
	- [ ] img_cat
	- [ ] img_stat
	- [ ] istat
	- [ ] jcat
	- [ ] jls
	- [ ] mmcat
	- [ ] mmls
	- [ ] mmstat
	- [ ] sigfind
	- [ ] tsk_comparedir
	- [ ] tsk_gettimes
	- [ ] tsk_loaddb
	- [ ] tsk_recover
--sleuthkit--

--- Reports ---
- [x] casefile
- [x] cutycapt
- [ ] dradis
- [x] metagoofil

--- SE ---
- [ ] phishing-frenzy - not a (pkg)

- [ ] system services
